# Generated by Django 5.2.5 on 2025-08-24 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('address', models.CharField(max_length=1024)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=255)),
                ('electricity', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('preview', models.FileField(blank=True, null=True, upload_to='bike/preview')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.station')),
            ],
        ),
    ]
