# Generated by Django 5.2.5 on 2025-08-29 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("capacity", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
            },
        ),
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("road", "Шоссейный"),
                            ("mtb", "Горный"),
                            ("city", "Городской"),
                            ("electric", "Электровелосипед"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("trek", "Trek"),
                            ("giant", "Giant"),
                            ("specialized", "Specialized"),
                            ("cube", "Cube"),
                            ("author", "Author"),
                        ],
                        max_length=50,
                        verbose_name="Bike Brand",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("red", "Красный"),
                            ("blue", "Синий"),
                            ("black", "Чёрный"),
                            ("white", "Белый"),
                            ("green", "Зелёный"),
                        ],
                        default="black",
                        max_length=20,
                        verbose_name="Colour",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "electricity",
                    models.BooleanField(
                        default=False, help_text="Есть ли у него педали"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Тут мы храним всю историю о велосипеде и его обслуживании",
                        null=True,
                        verbose_name="Bike History",
                    ),
                ),
                (
                    "preview",
                    models.FileField(blank=True, null=True, upload_to="bike/preview"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bikes",
                        to="bike.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bicycle",
                "verbose_name_plural": "Bicycles",
            },
        ),
    ]
