# Generated by Django 5.2.5 on 2025-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=255)),
                ('electricity', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('preview', models.FileField(blank=True, null=True, upload_to='bike/preview')),
            ],
        ),
    ]
