# Generated by Django 5.2.5 on 2025-08-27 20:27
from django.db import migrations


def forwards_func(apps, schema_editor):
    Bike = apps.get_model("bike", "Bike")
    Station = apps.get_model("bike", "Station")

    # Создаём станцию
    station, created = Station.objects.get_or_create(
        name="Pyshkinskaya",
        defaults={
            "address": "ул. Пушкинская, 123",
            "capacity": 20,
        },
    )

    # Создаём велосипед
    if not Bike.objects.filter(brand="trek", station=station).exists():
        Bike.objects.create(
            category="road",
            brand="trek",
            electricity=False,
            colour="black",
            available=True,
            comments="Новый велосипед Trek",
            station=station,
        )


def reverse_func(apps, schema_editor):
    Bike = apps.get_model("bike", "Bike")
    Station = apps.get_model("bike", "Station")

    station = Station.objects.filter(name="Pyshkinskaya").first()
    if station:
        Bike.objects.filter(brand="trek", station=station).delete()
    Station.objects.filter(name="Pyshkinskaya").delete()
class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func),]
