# Generated by Django 5.2.5 on 2025-08-24 19:32
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_populate_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name': 'Bicycle', 'verbose_name_plural': 'Bicycles'},
        ),
        migrations.RemoveField(
            model_name='bike',
            name='color',
        ),
        migrations.AddField(
            model_name='bike',
            name='colour',
            field=models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('black', 'Чёрный'), ('white', 'Белый'), ('green', 'Зелёный')], default='black', max_length=20, verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='bike',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(choices=[('trek', 'Trek'), ('giant', 'Giant'), ('specialized', 'Specialized'), ('cube', 'Cube'), ('author', 'Author')], max_length=50, verbose_name='Bike Brand'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(blank=True, choices=[('road', 'Шоссейный'), ('mtb', 'Горный'), ('city', 'Городской'), ('electric', 'Электровелосипед')], max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='comments',
            field=models.TextField(blank=True, help_text='Тут мы храним всю историю о велосипеде и его обслуживании', null=True, verbose_name='Bike History'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='electricity',
            field=models.BooleanField(default=False, help_text='Есть ли у него педали'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='bike.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
