# Generated by Django 5.2.5 on 2025-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_stations_bike_name_alter_bike_category_bike_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name': 'Bicycle', 'verbose_name_plural': 'Bicycles'},
        ),
        migrations.AlterModelOptions(
            name='stations',
            options={'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='comments',
            field=models.TextField(blank=True, help_text='Тут мы храним историю у велосипеде', null=True, verbose_name='Bike History'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='electricity',
            field=models.BooleanField(default=False, help_text='есть ли у него педали?'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
