# Generated by Django 5.2.5 on 2025-08-19 18:27

from django.db import migrations


def forwards_func(apps, schema_editor):
    # Получаем модели через apps.get_model()
    Bike = apps.get_model('bike', "Bike")
    Stations = apps.get_model('bike', "Stations")

    # Создаем станцию
    new_station = Stations.objects.create(
        name="Pyshkinskaya",
        address="ул. Пушкинская, 123",
        capacity=20,
    )

    # Создаем велосипед
    Bike.objects.create(
        category="Городской",
        name="Stels Navigator 500",
        brand="Stels",
        electricity=False,
        color="Black",
        available=True,
        comments="Новый велосипед, в отличном состоянии",
        preview=None,  # можно оставить пустым
        station=new_station
    )


def reverse_func(apps, schema_editor):
    # Логика для отката миграции
    Bike = apps.get_model('bike', "Bike")
    Stations = apps.get_model('bike', "Station")

    # Удаляем созданные объекты
    Bike.objects.filter(name="Stels Navigator 500").delete()
    Stations.objects.filter(name="Pyshkinskaya").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_alter_bike_options_alter_stations_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=forwards_func,
            reverse_code=reverse_func),
    ]
