# Generated by Django 5.2.5 on 2025-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_create_one_bike_station'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='color',
        ),
        migrations.AddField(
            model_name='bike',
            name='colour',
            field=models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('black', 'Чёрный'), ('white', 'Белый'), ('green', 'Зелёный'), ('other', 'Другой')], default='black', max_length=20, verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='bike',
            name='custom_brand',
            field=models.CharField(blank=True, help_text="Укажите, если выбрано 'Другая'", max_length=100, null=True, verbose_name='Другой бренд'),
        ),
        migrations.AddField(
            model_name='bike',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Укажите, если выбрано 'Другое'", max_length=100, null=True, verbose_name='Другая категория'),
        ),
        migrations.AddField(
            model_name='bike',
            name='custom_colour',
            field=models.CharField(blank=True, help_text="Укажите, если выбрано 'Другой'", max_length=100, null=True, verbose_name='Другой цвет'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(choices=[('trek', 'Trek'), ('giant', 'Giant'), ('specialized', 'Specialized'), ('cube', 'Cube'), ('author', 'Author'), ('other', 'Другая')], max_length=50, verbose_name='Bike Brand'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='category',
            field=models.CharField(blank=True, choices=[('road', 'Шоссейный'), ('mtb', 'Горный'), ('city', 'Городской'), ('electric', 'Электровелосипед'), ('other', 'Другое')], max_length=20, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='comments',
            field=models.TextField(blank=True, help_text='Тут мы храним всю историю о велосипеде и его обслуживании', null=True, verbose_name='Bike History'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='electricity',
            field=models.BooleanField(default=False, help_text='Есть ли у него педали'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
